select * from bronze.erp_px_cat_g1v2;

select 
TRIM(ID) AS ID,
TRIM(CAT) AS CAT,
TRIM(SUBCAT) AS SUBCAT,
TRIM(MAINTENANCE) AS MAINTENANCE
FROM bronze.erp_px_cat_g1v2;


--INSPECTING DUPLICATES OR NULL OR  UNANTED SPACES IN BUSINESS KEY

SELECT * FROM bronze.erp_px_cat_g1v2 
WHERE ID IS NULL;

SELECT ID,
COUNT(*) AS DUPLICATE
FROM bronze.erp_px_cat_g1v2
GROUP BY ID
HAVING COUNT(*) >1;

SELECT ID,CAT,SUBCAT,MAINTENANCE ,
COUNT(*) AS DUPLICATE
FROM bronze.erp_px_cat_g1v2
GROUP BY ID,CAT,SUBCAT,MAINTENANCE
HAVING COUNT(*) > 1;

SELECT * FROM bronze.erp_px_cat_g1v2
WHERE MAINTENANCE != TRIM(MAINTENANCE);